name: vcars

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
  memcached:
    image: memcached:1.6.21
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
  celery:
    build: .
    command: celery -A celeryapp worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres-data: