# Generated by Django 5.1 on 2024-08-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
