# Generated by Django 5.1 on 2024-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcars', '0002_pic_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='thumb',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
