# Generated by Django 5.1 on 2024-08-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcars', '0003_alter_pic_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='thumb',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
