# Generated by Django 5.1 on 2024-08-30 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcars', '0004_alter_pic_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcars.pic')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='vcars_comme_created_219e3a_idx')],
            },
        ),
    ]
