# Generated by Django 5.1 on 2024-09-09 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcars', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='pic',
            field=models.ImageField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'webp', 'jpeg', 'png'])]),
        ),
    ]
