# Generated by Django 5.1 on 2024-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcars', '0006_alter_pic_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
