# Generated by Django 5.1 on 2024-10-28 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcars', '0008_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='vcars_comme_created_219e3a_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vcars.pic'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='vcars_comme_created_a8fcd7_idx'),
        ),
    ]
